Configuration:
  status: warn
  Appenders:
    File:
      name: File_Appender
      fileName: logfile.log
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    Console:
      name: LogToConsole
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d [%t] %-5p %c - %m%n"
  Loggers:
    Logger:
      - name: test.stepdef
        additivity: true
        level: debug
        AppenderRef:
          - ref: LogToConsole
    Root:
      level: trace
      AppenderRef:
          -  ref: File_Appender      